version: '3.1'

services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
    - "27017:27017"

  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - ./src:/app/src